import { useEffect, useMemo, useState } from "react";
const euro = new Intl.NumberFormat("nl-NL", { style: "currency", currency: "EUR" });

export default function JoybuyPage() {
  const [data, setData] = useState(null); const [query, setQuery] = useState("");
  useEffect(() => { fetch("./data/joybuy-offers.json").then((r) => r.json()).then(setData).catch(() => setData({ error: true, offers: [] })); }, []);
  const offers = useMemo(() => (data?.offers ?? []).filter((o) => `${o.name} ${o.nameZh}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => b.discountPercent - a.discountPercent), [data, query]);
  if (!data) return <main className="loading">正在读取 Joybuy 食品闪电优惠…</main>;
  if (data.error) return <main className="loading">Joybuy 数据暂不可用。</main>;
  return <main className="page joybuy-page"><header className="hero joybuy-hero"><div className="stamp joybuy-stamp">JOY<br />BUY</div><div><p className="kicker">荷兰公开站 · 食品与饮料</p><h1>食品闪电价，<em>先看</em>再买。</h1><p className="subhead">仅采集未登录可见的商品、价格和评价信息。</p></div><div className="update"><b>{data.offers.length}</b><span>项食品优惠<br />本次公开页更新</span></div></header><nav className="shop-switch"><a href="./">Dirk 超市</a><a className="selected" href="?shop=joybuy">Joybuy 闪电优惠</a></nav><section className="catalogue joybuy-catalogue"><div className="catalogue-head"><div><span>公开食品闪电优惠 · {offers.length} 项</span><h2>折扣先排好，再决定要不要点开。</h2></div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索中文或荷兰原名" aria-label="搜索 Joybuy 食品优惠" /></div><div className="offer-grid joybuy-grid">{offers.map((o) => <article className="offer joybuy-offer" key={o.productUrl}><div className="photo"><img src={o.imageUrl} alt={o.nameZh} loading="lazy" /><span>−{o.discountPercent}%</span></div><div className="offer-body"><p className="category">JOYBUY · 食品闪电优惠</p><h3>{o.nameZh}</h3><p className="pack">{o.name}</p><p className="joybuy-meta">{o.rating && `评分 ${o.rating}`} {o.sold && ` · ${o.sold}`}</p><div className="price"><b>{euro.format(o.sale)}</b>{o.original && <s>{euro.format(o.original)}</s>}</div><p className="advice">{o.advice}</p><a className="product-link" href={o.productUrl} target="_blank" rel="noreferrer">在 Joybuy 查看商品 ↗</a></div></article>)}</div></section><footer>数据来自未登录可见的 Joybuy 食品闪电优惠页面；价格与规格以商品页为准。</footer></main>;
}
